name: lint
on: [push, pull_request]

permissions:
  contents: read

jobs:
  golangci:
    name: go-lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Check golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --config ./.golangci.yml ./...
